bot_token: "OTkzMTE0ODcwNDAyNzgxMTg1.Ggc5zf.HCIRL4_35ScsbY5y8d76I7eo58usrVIlZj4tdA"
selfbot_token: "OTI3MjUzMDM2MzAzMjY1ODYz.G2z1z5.fD4Wvkh98eKGf0WcOI3qBYLxzokEUemZh2H1jo"

arcane_id: 437808476106784770
disboard_id: 302050872383242240

newbie_level: 3

postgres:
  host: "localhost"
  port: 5432
  database: "memes"
  user: "postgres"
  password: "123123"
